directories = [
  "/Users/travisennis/.cake",
  "/Users/travisennis/.cache/cake",
  "/Users/travisennis/.local/share/cake",
  "/Users/travisennis/.config/cake",
  "/Users/travisennis/.local/bin",
  "/Users/travisennis/.config/notion",
]
